import LineChart from '@/components/charts/line-chart';
import AdminHeader from '@/components/common/admin-header'
import Footer from '@/components/common/footer';
import SideMenu from '@/components/sideMenu'
import { RingProgress, Text } from '@mantine/core'
import Head from 'next/head'







export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <div className='admin_wrap container-fluid'>
          <SideMenu />
          <div className="admin-content-area">
            <AdminHeader />
            <div className="dashboard-widget-wrap">
              <div className="row">

                {/** Professional Admin Registered */}
                <div className="admin-wedget content-center col-lg-6">
                  <RingProgress
                    size={138}
                    thickness={12}
                    rootColor="rgba(71, 182, 244, .15)"
                    roundCaps={true}
                    sections={[{ value: 70, color: '#47B6F4' }]}
                    label={
                      <div className='label'>163</div>
                    }
                  />
                  <h2 className='card-title'>Professional Admin Registered</h2>
                  <p>There are many variations of passages of Lorem Ipsum available.</p>
                </div>


                {/** Clients Onboarded */}
                <div className="admin-wedget content-center col-lg-6">
                  <RingProgress
                    size={138}
                    thickness={12}
                    rootColor="rgba(71, 182, 244, .15)"
                    roundCaps={true}
                    sections={[{ value: 70, color: '#47B6F4' }]}
                    label={
                      <div className='label'>100</div>
                    }
                  />
                  <h2 className='card-title'>Professional Admin Registered</h2>
                  <p>There are many variations of passages of Lorem Ipsum available.</p>
                </div>

                {/** Total Revenue generated */}
                <div className="admin-wedget content-center col-lg-6">
                  <RingProgress
                    size={138}
                    thickness={12}
                    rootColor="rgba(71, 182, 244, .15)"
                    roundCaps={true}
                    sections={[{ value: 70, color: '#9DCB55' }]}
                    label={
                      <div className='label green'>$123</div>
                    }
                  />
                  <h2 className='card-title'>Total Revenue generated</h2>
                  <p>There are many variations of passages of Lorem Ipsum available.</p>
                </div>

                {/** Monthly Sales */}
                <div className="admin-wedget content-center col-lg-6">

                  <h2 className='card-title'>Monthly Sales</h2>
                  <LineChart />

                </div>



              </div>

            </div>
          </div>
        </div>
        <Footer />
      </>
    </>
  )
}
