export const PROFESSIONAL_ADMIN_SIGNUP = "PROFESSIONAL_ADMIN_SIGNUP";
export const PROFESSIONAL_ADMIN_SIGNUP_ERROR = "PROFESSIONAL_ADMIN_SIGNUP_ERROR";
export const PROFESSIONAL_ADMIN_DETAILS = "PROFESSIONAL_ADMIN_DETAILS";
export const PROFESSIONAL_ADMIN_DETAILS_ERROR = "PROFESSIONAL_ADMIN_DETAILS_ERROR";
export const PROFESSIONAL_CLIENT_DETAILS = "PROFESSIONAL_CLIENT_DETAILS";
export const PROFESSIONAL_CLIENT_DETAILS_ERRORS = "PROFESSIONAL_CLIENT_DETAILS_ERRORS";
export const DASHBOARD_CLIENT_LIST = "DASHBOARD_CLIENT_DETAILS";
export const DASHBOARD_CLIENT_LIST_ERRORS = "DASHBOARD_CLIENT_DETAILS_ERRORS";



