export const AUTH_LOGIN_START = "AUTH_LOGIN_START";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_ERROR = "AUTH_ERROR";
export const PROFESSIONAL_ADMIN_SIGNUP = "PROFESSIONAL_ADMIN_SIGNUP";
export const PROFESSIONAL_ADMIN_SIGNUP_ERROR = "PROFESSIONAL_ADMIN_SIGNUP_ERROR";

export const PROFESSIONAL_ADMIN_DETAILS = "PROFESSIONAL_ADMIN_DETAILS";
export const PROFESSIONAL_ADMIN_DETAILS_ERROR = "PROFESSIONAL_ADMIN_DETAILS_ERROR";

export const PROFESSIONAL_ADMIN_EDIT = "PROFESSIONAL_ADMIN_DETAILS";
export const PROFESSIONAL_ADMIN_EDIT_ERRORS = "PROFESSIONAL_ADMIN_DETAILS_ERROR";

export const   CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";


// export const PROFESSIONAL_MANAGER_LIST = "PROFESSIONAL_MANAGER_LIST";
// export const PROFESSIONAL_MANAGER_LIST_ERROR = "PROFESSIONAL_MANAGER_LIST_ERROR";

export const ADMIN_CLIENT_DETAILS = "ADMIN_CLIENT_DETAILS";
export const ADMIN_CLIENT_DETAILS_ERRORS = "ADMIN_CLIENT_DETAILS_ERRORS";
export const DASHBOARD_CLIENT_LIST = "DASHBOARD_CLIENT_DETAILS";
export const DASHBOARD_CLIENT_LIST_ERRORS = "DASHBOARD_CLIENT_DETAILS_ERRORS";
export const ADMIN_CLIENT_DETAILS_UPDATE = "ADMIN_CLIENT_DETAILS_UPDATE ";
export const ADMIN_CLIENT_DETAILS_UPDATE_ERRORS = "ADMIN_CLIENT_DETAILS_UPDATE_ERRORS";
export const INVITE_CLIENT = "INVITE_CLIENT";
export const INVITE_CLIENT_ERROR = "INVITE_CLIENT_ERROR"

export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const FORGET_PASSWORD_ERROR = "FORGET_PASSWORD_ERROR";
export const VERIFY_TOKEN  = "VERIFY_TOKEN";
export const VERIFY_TOKEN_ERROR = "VERIFY_TOKEN_ERROR";

export const PROFESSIONAL_ADMIN_MANAGER_LIST = "PROFESSIONAL_ADMIN_MANAGER_LIST";
export const PROFESSIONAL_ADMIN_MANAGER_LIST_ERRORS = "PROFESSIONAL_ADMIN_MANAGER_LIST_ERRORS";
export const PROFESSIONAL_ADMIN_ADD_PROFESSIONAL_MANAGER = "PROFESSIONAL_ADMIN_ADD_PROFESSIONAL_MANAGER";
export const PROFESSIONAL_ADMIN_ADD_PROFESSIONAL_MANAGER_ERRORS = "PROFESSIONAL_ADMIN_ADD_PROFESSIONAL_MANAGER_ERRORS";
export const PROFESSIONAL_MANAGER_DETAILS = "PROFESSIONAL_MANAGER_DETAILS";
export const PROFESSIONAL_MANAGER_DETAILS_ERROR = "PROFESSIONAL_MANAGER_DETAILS_ERROR"
export const  PROFESSIONAL_ADMIN_UPDATE_PROFESSIONAL_MANAGER = "PROFESSIONAL_ADMIN_UPDATE_PROFESSIONAL_MANAGER";
export const PROFESSIONAL_ADMIN_UPDATE_PROFESSIONAL_MANAGER_ERRORS = "PROFESSIONAL_ADMIN_UPDATE_PROFESSIONAL_MANAGER_ERRORS";

